import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import useTrackLocation from '../hooks/use-track-location';
import Banner from '../components/Banner/Banner.component';
import { fetchCoffeeStores } from '../lib/coffee-stores';
import Card from '../components/Card/Card.component';
import styles from '../styles/Home.module.css';

export const getStaticProps = async () => {
	const coffeeStores = await fetchCoffeeStores();

	return {
		props: {
			coffeeStores,
		},
	};
};

export default function Home(props) {
	const [coffeeStores, setCoffeeStores] = useState({});
	const [coffeeStoreError, setCoffeeStoreError] = useState(null);
	const {
		latLong,
		locationErrorMsg,
		setLocationErrorMsg,
		isFindingLocation,
		setIsFindingLocation,
	} = useTrackLocation();

	const handleOnBannerBtnClick = () => {
		const getCoffeeStores = async () => {
			if (latLong) {
				try {
					setIsFindingLocation(true);
					setLocationErrorMsg('');
					const coffeeStores = await fetchCoffeeStores(latLong, 30);
					setCoffeeStores(coffeeStores);
					setIsFindingLocation(false);
				} catch (error) {
					setCoffeeStoreError(error.message);
					setIsFindingLocation(false);
				}
			}
		};

		getCoffeeStores();
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText={isFindingLocation ? 'Locating...' : 'View stores nearby'}
					handleOnClick={handleOnBannerBtnClick}
				/>
				{locationErrorMsg && <p>Something went wrong: {locationErrorMsg}</p>}
				<div className={styles.heroImage}>
					<Image
						src='/static/hero-image.png'
						width={700}
						height={400}
						alt='hero-image'
					/>
				</div>
				{coffeeStoreError.length ? (
					<p>{error}</p>
				) : (
					coffeeStores.length && (
						<div className={styles.sectionWrapper}>
							<h2 className={styles.heading2}>Stores near me</h2>
							<div className={styles.cardLayout}>
								{coffeeStores.map(store => (
									<Card
										key={store.id}
										store={store}
										href={`/coffee-store/${store.id}`}
										className={styles.card}
									/>
								))}
							</div>
						</div>
					)
				)}
				{props.coffeeStores.length && (
					<div className={styles.sectionWrapper}>
						<h2 className={styles.heading2}>Toronto stores</h2>
						<div className={styles.cardLayout}>
							{props.coffeeStores.map(store => (
								<Card
									key={store.id}
									store={store}
									href={`/coffee-store/${store.id}`}
									className={styles.card}
								/>
							))}
						</div>
					</div>
				)}
			</main>
		</div>
	);
}
